/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AreaMap: typeof import('./src/components/AreaMap.vue')['default']
    Dashboard: typeof import('./src/components/Dashboard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimezoneMap: typeof import('./src/components/TimezoneMap.vue')['default']
    UnitMenu: typeof import('./src/components/UnitMenu.vue')['default']
  }
}
