import vuetify from 'eslint-config-vuetify'

export default vuetify({
  rules: {
    'vue/padding-line-between-tags': 'off',
    '@typescript-eslint/member-ordering': 'off',
    '@typescript-eslint/no-invalid-this': 'off',
    'prefer-const': ['error', {
      dstructuring: 'any',
      ignoreReadBeforeAssign: false,
    }],
    '@stylistic/quote-props': 'off',
    'perfectionist/sort-imports': 'off',
    'perfectionist/sort-named-exports': 'off',
    'perfectionist/sort-named-imports': 'off',
    'perfectionist/sort-exports': 'off',
    'unicorn/no-array-for-each': 'off',
    'unicorn/switch-case-braces': 'off',
    'unicorn/prefer-ternary': 'off',
    'unicorn/prefer-structured-clone': 'off',
    'unicorn/no-negated-condition': 'off',
    'unicorn/no-new-array': 'off',
    'unicorn/no-for-loop': 'off',
    'unicorn/no-array-callback-reference': 'off',
    'unicorn/prefer-dom-node-dataset': 'off',
    'unicorn/no-this-outside-of-class': 'off',
    'unicorn/prefer-code-point': 'off',
    'unicorn/catch-error-name': 'off',
    'unicorn/no-document-cookie': 'off',
    'unicorn/prefer-at': 'off',
    'unicorn/no-static-only-class': 'off',
    'unicorn/prefer-dom-node-append': 'off',
    'unicorn/prefer-dom-node-remove': 'off',
    'unicorn/prefer-query-selector': 'off',
    'unicorn/no-array-sort': 'off',
    'unicorn/no-array-reverse': 'off',
    'unicorn/prefer-classlist-toggle': 'off',
    'unicorn/prefer-number-properties': 'off',
    'unicorn/prefer-add-event-listener': 'off',
    'vue/attributes-order': 'off',
    'vue/max-attributes-per-line': 'off',
    'vue/order-in-components': 'off',
  },
})
